version: '3.8'

services:
  
  backend:
    depends_on:
      - mysql-container
    build: ./backend
    restart: unless-stopped
    ports:
      - "9897:9897"
    # volumes:
    #   - backend-data:/backend-app
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASSWORD=mysql
      - DB_NAME=bookstores



  frontend:
    depends_on:
      - backend
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://127.0.0.1:9897
        
    # volumes:
    #   - frontend-data:/frontend-app
    ports:
      - "3000:3000"



  mysql-container:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=bookstores
    ports:
      - "3306:3306"
    volumes:
      # - db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

# volumes: 
#   db:
#   backend-data:
#   frontend-data:
